server:
  port: 9955
spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/meeting?useUnicode=true&characterEncoding=utf-8
    username: root
    password: gon_Wee_123
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 10MB
      
mybatis:
  type-aliases-package: com.gonwee.archives.mapper
  mapper-locations: classpath:mapper/*.xml

  
logging:
  path: meeting-logs