server:
  port: 7777
spring:
  thymeleaf:
    cache: false
    mode: LEGACYHTML5
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.16.10.99:3306/chaoyang-archives?useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB

mybatis:
  type-aliases-package: com.gonwee.archives.mapper
  mapper-locations: classpath:mapper/*.xml
